name: Build, Scan and Upload Docker Image

on:
  push:
    tags:
      - '*'

env:
  REGION: europe-west2
  PROJECT: sonorous-wharf-424609-c1
  REPO: main
  IMAGE: demo-1
  GCP_CLOUD_RUN_SERVICE: demo-1
  DOTNET_CORE_VERSION: 7.0.x
  SOLUTION_NAME: ccse_cw1.sln

permissions:
  issues: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set vars
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE" >> $GITHUB_ENV

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GC_IMAGE_MANAGER_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  sast-scan:
    needs: build-push
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      
      - name: Restore project dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}

      - name: Run Snyk to check application for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: snyk-sast-analysis

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GC_IMAGE_MANAGER_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Enable Cloud Run API
        run: gcloud services enable run.googleapis.com

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy demo-1 \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.ref_name }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --project ${{ env.PROJECT }} \
            --allow-unauthenticated \
            --format "value(status.url)"

  dast-scan:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GC_IMAGE_MANAGER_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Get Cloud Run Service URL
        id: get-url
        run: |
          URL=$(gcloud run services describe ${{ env.GCP_CLOUD_RUN_SERVICE }} --region=${{ env.REGION }} --format 'value(status.url)')
          echo "::set-output name=url::$URL"

      - name: Set up OWASP ZAP
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: ${{ steps.get-url.outputs.url }}

      - name: Create GitHub Issue on Alerts
        if: failure()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"OWASP ZAP Scan Alerts","body":"OWASP ZAP scan found vulnerabilities. Please check the details and address them accordingly."}'
